apiVersion: v1
kind: Secret
metadata:
  name: app-secrets # Name of the Secret
  labels:
    app: demo-app
    component: secrets
    environment: development
type: Opaque # Most common secret type for arbitrary data
stringData: # Plain text data (automatically base64 encoded)
  # Database credentials
  database_username: "appuser"
  database_password: "supersecretpassword123"
  database_url: "postgresql://appuser:supersecretpassword123@postgres:5432/demo_app"
  
  # API keys and tokens
  api_key: "your-secret-api-key-here"
  jwt_secret: "your-256-bit-jwt-secret-key"
  stripe_api_key: "sk_test_your_stripe_key_here"
  
  # External service credentials
  redis_password: "redis-secret-password"
  smtp_password: "smtp-email-password"
  
  # Application secrets
  encryption_key: "32-character-encryption-key-here"
  session_secret: "session-signing-secret-key"
  
  # Configuration file with sensitive data
  database.conf: |
    [database]
    host = postgres.example.com
    port = 5432
    username = appuser
    password = supersecretpassword123
    database = demo_app
    sslmode = require
    max_connections = 20
    connection_timeout = 30
    
    [cache]
    redis_host = redis.example.com
    redis_port = 6379
    redis_password = redis-secret-password
    redis_db = 0
    
    [security]
    jwt_secret = your-256-bit-jwt-secret-key
    encryption_key = 32-character-encryption-key-here
    session_timeout = 3600
---
# TLS Secret for HTTPS certificates
apiVersion: v1
kind: Secret
metadata:
  name: demo-tls-secret
  labels:
    app: demo-app
    component: tls
type: kubernetes.io/tls # Specific type for TLS certificates
stringData:
  # Self-signed certificate for demo (in production, use real certificates)
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDXTCCAkWgAwIBAgIJAKL0wU8VQKzQMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
    BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
    aWRnaXRzIFB0eSBMdGQwHhcNMjMxMDAxMTAwMDAwWhcNMjQxMDAxMTAwMDAwWjBF
    MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
    ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEAwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSd
    wU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQ
    ZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU
    8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZl
    HmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwIDA
    QABo1AwTjAdBgNVHQ4EFgQUwU8VQKzQZlHmSdwU8VQKzQZlHmSdwAfBgNVHSMEGD
    AWgBTBTxVArNBmUeZJ3BTxVQrNBmUeZJ3DAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3
    DQEBCwUAA4IBAQAwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKz
    QZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdw
    U8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQ
    ZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdw=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDBTxVArNBmUeZJ
    3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArN
    BmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3B
    TxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBm
    UeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTx
    VArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJwIDAQABAoIBAAwU8VQKzQZlHmSd
    wU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQ
    ZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU
    8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZl
    HmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8V
    QKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHm
    SdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwECgYEAwU8VQKzQZlHm
    SdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQK
    zQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSd
    wU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwECgYEA
    wU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQ
    ZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU
    8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZl
    HmSdwQJ5BAgEAAoGBAMFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPF
    UCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5
    kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUC
    s0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5knc=
    -----END PRIVATE KEY-----
---
# Docker registry secret for private images
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    app: demo-app
    component: registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "private-registry.example.com": {
          "username": "registry-user",
          "password": "registry-password",
          "email": "user@example.com",
          "auth": "cmVnaXN0cnktdXNlcjpyZWdpc3RyeS1wYXNzd29yZA=="
        },
        "docker.io": {
          "username": "dockerhub-user", 
          "password": "dockerhub-password",
          "email": "user@example.com",
          "auth": "ZG9ja2VyaHViLXVzZXI6ZG9ja2VyaHViLXBhc3N3b3Jk"
        }
      }
    }
---
# Basic authentication secret
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  labels:
    app: demo-app
    component: auth
type: kubernetes.io/basic-auth
stringData:
  username: "admin"
  password: "admin-secret-password"
---
# SSH key secret for git operations
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-secret
  labels:
    app: demo-app
    component: git
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAQEAwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQ
    ZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8V
    QKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSd
    wU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZl
    HmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQK
    zQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwAAAAMBAAEAAABAAwU8VQKzQZlHmSd
    wU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZl
    HmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQK
    zQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU
    8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHm
    SdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwAAACBAM
    FPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR
    5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs
    0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncFPFUCs0GZR5kncAAAAgQDBTxVArNBm
    UeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVA
    rNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3B
    TxVArNBmUeZJ3BTxVArNBmUeZJ3BTxVArNBmUeZJ3AAAAIEAwU8VQKzQZlHmSdwU8V
    QKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSd
    wU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZl
    HmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwAAAAR1demoLAGzQZlHmSdwU8VQKzQZlHm
    SdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQ
    ZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8V
    QKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSd
    wU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZl
    HmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQK
    zQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU
    8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHm
    SdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQ
    ZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8V
    QKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSdwU8VQKzQZlHmSN
    -----END OPENSSH PRIVATE KEY-----
  # Optional: known_hosts file for SSH connections  
  known_hosts: |
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==